package com.layerdocs.rendering.html.post.resources

import com.layerdocs.core.pipeline.output.OutputResource
import com.layerdocs.core.rendering.PostRenderer

/**
 * A [PostRendererResource] that delegates resource generation to another [PostRenderer].
 *
 * This enables composition of post-renderers by including resources
 * generated by a base renderer (e.g., [com.layerdocs.rendering.html.post.HtmlOnlyPostRenderer])
 * as part of the current output.
 *
 * @param base the post-renderer whose generated resources will be included
 */
class ProxiedPostRendererResource(
    private val base: PostRenderer,
) : PostRendererResource {
    override fun includeTo(
        resources: MutableSet<OutputResource>,
        rendered: CharSequence,
    ) {
        resources += base.generateResources(rendered)
    }
}
