package com.layerdocs.core.flavor.layerdocs

import com.layerdocs.core.flavor.base.BaseMarkdownParserFactory

/**
 * [LayerDocsFlavor] parser factory.
 * LayerDocs parsing doesn't differ from the base one, as new nodes are generated by the lexer,
 * instead of the parser.
 */
typealias LayerDocsParserFactory = BaseMarkdownParserFactory
