package com.layerdocs.core.ast.attributes.reference

import com.layerdocs.core.ast.Node
import com.layerdocs.core.context.Context
import com.layerdocs.core.context.MutableContext

/** Represents a node that may reference some definition that is generated by elsewhere in the document.
 *
 * Examples:
 * - [com.layerdocs.core.ast.base.inline.ReferenceLink] refers to a [com.layerdocs.core.ast.base.LinkNode]
 * - [com.layerdocs.core.ast.base.inline.ReferenceFootnote] refers to a [com.layerdocs.core.ast.base.block.FootnoteDefinition]
 * - [com.layerdocs.core.ast.layerdocs.bibliography.BibliographyCitation] refers to a [com.layerdocs.core.bibliography.BibliographyEntry]
 *
 * @param R the type of the reference element
 * @param D the type of the definition associated with the reference
 */
interface ReferenceNode<R, D> : Node {
    /**
     * The reference element to associate with the definition.
     */
    val reference: R
}

/**
 * @param context context where the [ResolvedReferenceProperty] is stored
 * @return the definition associated with [this] reference within the document handled by [context],
 * or `null` if the definition for [this] node is not registered or resolved
 */
fun <R, D> ReferenceNode<R, D>.getDefinition(context: Context): D? =
    context.attributes
        .of(this)[ResolvedReferenceProperty.Key<R, D>()]
        ?.second

/**
 * Registers the given [definition] as the definition associated with [this] reference within the document handled by [context].
 * @param context context where the [ResolvedReferenceProperty] is stored
 * @param definition the definition to associate with [this] reference
 * @see com.layerdocs.core.context.hooks.reference.ReferenceDefinitionResolverHook for the assignment stage
 */
fun <R, D> ReferenceNode<R, D>.setDefinition(
    context: MutableContext,
    definition: D,
) {
    context.attributes.of(this) += ResolvedReferenceProperty(this.reference to definition)
}
